"""change_pk_in_product_and_cange_relationship_in_subsctiption

Revision ID: 02bf1912761e
Revises: 116012c370cc
Create Date: 2024-03-09 10:35:40.301494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02bf1912761e'
down_revision: Union[str, None] = '116012c370cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
