"""change_pk_in_product_and_cange_relationship_in_subsctiption

Revision ID: 116012c370cc
Revises: 3a0c4318f444
Create Date: 2024-03-08 22:34:03.534619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116012c370cc'
down_revision: Union[str, None] = '3a0c4318f444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_id_key', 'product', type_='unique')
    op.drop_column('product', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('product_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.create_unique_constraint('product_id_key', 'product', ['id'])
    # ### end Alembic commands ###
