"""add_ordering_to_products

Revision ID: 1eb7ea84e3b6
Revises: a17879256d2a
Create Date: 2024-03-10 12:40:29.821389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb7ea84e3b6'
down_revision: Union[str, None] = 'a17879256d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
