"""unique_article_id_user_id

Revision ID: e969332c9805
Revises: bf1c9926d1f5
Create Date: 2024-03-08 21:13:50.395080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e969332c9805'
down_revision: Union[str, None] = 'bf1c9926d1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint('unique_constraint_user_id_article_id', 'subscription', ['user_id', 'article_id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint('unique_constraint_user_id_article_id', 'subscription', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    # ### end Alembic commands ###
