"""change_pk_in_product_and_cange_relationship_in_subsctiption

Revision ID: f0552ebc178d
Revises: 88f8cd47a666
Create Date: 2024-03-09 12:03:26.681836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0552ebc178d'
down_revision: Union[str, None] = '88f8cd47a666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
